# 1. Cấu hình Server
server.port=8080

# 2. Cấu hình Database (Kết nối tới service "database" trong compose.yaml)
spring.datasource.url=jdbc:postgresql://database:5432/timetablex_db
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Cấu hình JPA / Hibernate
# Tự động cập nhật schema database khi sửa code Java (Entity)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true